#!/usr/bin/env python3
"""Generate the app's icon set from the project's decided mark.

Source of truth is ../../docs/icon/mark.svg (generated by docs/icon/build_marks.py), plus the
family's shared h-solid.svg and h-16.svg. Never hand-edit the PNGs; re-run this instead.

The tile matches Huck's Snip 'n' Clip exactly (hucks-snip-n-clip/app/mac/Resources/
generate-app-icon.swift), so the programs read as one family: a light grey rounded tile, the H
in near-black filling the same 6->58 span of the 64-unit grid, and the interior knocked out to
clear alpha. Changed 2026-09-25 from a placeholder dark slate tile with a small white H.
"""
import re
import shutil
import subprocess
from pathlib import Path
from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parents[2]
ICON_DIR = ROOT / "docs" / "icon"
OUT = ROOT / "app" / "desktop" / "icons"

TILE = (224, 224, 224, 255)   # Snip 'n' Clip: gray 0.88
INK = (10, 10, 10, 255)       # Snip 'n' Clip: gray 0.04
SUPERSAMPLE = 4


def subpaths(d: str) -> list[list[tuple[float, float]]]:
    """Parse an M/L/H/V/Z path into closed polygons. The mark uses nothing else."""
    polys, cur, x, y = [], [], 0.0, 0.0
    for cmd, args in re.findall(r"([MLHVZ])([^MLHVZ]*)", d):
        nums = [float(n) for n in re.findall(r"-?\d*\.?\d+", args)]
        if cmd == "M":
            if cur:
                polys.append(cur)
            x, y = nums[0], nums[1]
            cur = [(x, y)]
            nums = nums[2:]
            cmd = "L"  # implicit lineto after moveto
        if cmd == "L":
            for i in range(0, len(nums), 2):
                x, y = nums[i], nums[i + 1]
                cur.append((x, y))
        elif cmd == "H":
            for n in nums:
                x = n
                cur.append((x, y))
        elif cmd == "V":
            for n in nums:
                y = n
                cur.append((x, y))
        elif cmd == "Z":
            polys.append(cur)
            cur = []
    if cur:
        polys.append(cur)
    return polys


def mark_polys() -> list[list[tuple[float, float]]]:
    svg = (ICON_DIR / "mark.svg").read_text()
    d = re.search(r'<path[^>]*\sd="([^"]+)"', svg).group(1)
    return subpaths(d)


def masks(side: int, polys) -> tuple[Image.Image, Image.Image]:
    """(ink, knockout) coverage masks at `side` px. The first subpath is the letter; the rest are
    the interior, which build_marks.py guarantees are inside it and never overlap."""
    big = side * SUPERSAMPLE
    scale = big / 64
    letter = Image.new("L", (big, big), 0)
    holes = Image.new("L", (big, big), 0)
    ImageDraw.Draw(letter).polygon([(x * scale, y * scale) for x, y in polys[0]], fill=255)
    hd = ImageDraw.Draw(holes)
    for p in polys[1:]:
        hd.polygon([(x * scale, y * scale) for x, y in p], fill=255)
    ink = Image.composite(Image.new("L", (big, big), 0), letter, holes)
    return (ink.resize((side, side), Image.LANCZOS), holes.resize((side, side), Image.LANCZOS))


def h16_mask() -> Image.Image:
    """The shared hand-tuned 16 px H, drawn on its own pixel grid."""
    m = Image.new("L", (16, 16), 0)
    d = ImageDraw.Draw(m)
    svg = (ICON_DIR / "h-16.svg").read_text()
    for x, y, w, h in re.findall(
        r'<rect x="(\d+)" y="(\d+)" width="(\d+)" height="(\d+)"', svg
    ):
        x, y, w, h = int(x), int(y), int(w), int(h)
        d.rectangle([x, y, x + w - 1, y + h - 1], fill=255)
    return m


def app_icon(side: int, polys) -> Image.Image:
    """Snip 'n' Clip's tile with this product's mark on it."""
    big = side * SUPERSAMPLE
    tile = Image.new("L", (big, big), 0)
    inset = max(0.5, big / 128)
    ImageDraw.Draw(tile).rounded_rectangle(
        [inset, inset, big - inset, big - inset], radius=big * 0.22, fill=255
    )
    tile = tile.resize((side, side), Image.LANCZOS)

    if side == 16:
        ink, holes = h16_mask(), Image.new("L", (16, 16), 0)
    elif side < 32:
        # Below 32 px the interior clogs (docs/icon-spec.md): the solid letter only.
        ink, holes = masks(side, [polys[0]])
    else:
        ink, holes = masks(side, polys)

    # Knockouts are clear alpha through the tile, exactly like Snip 'n' Clip's.
    alpha = Image.composite(Image.new("L", (side, side), 0), tile, holes)
    img = Image.new("RGBA", (side, side), TILE)
    img = Image.composite(Image.new("RGBA", (side, side), INK), img, ink)
    img.putalpha(alpha)
    return img


def tray_icon(side: int, polys) -> Image.Image:
    """Menu bar: a template image (alpha only) of the full mark, sound arcs and words included.
    Changed 2026-09-25 at Quintin's direction - a plain H did not read as this program, and Snip
    'n' Clip's menu-bar H carries its interior too. Overrides the size-band note in icon-spec."""
    # At 18 pt the 2-unit word blocks fall to one faint pixel, so the menu-bar master sets them
    # half again as tall. They stay inside the letter's interior clip (rows at y 25, 32, 39).
    def taller(poly):
        if min(x for x, _ in poly) < 38:
            return poly  # the letter or an arc
        mid = sum(y for _, y in poly) / len(poly)
        return [(x, mid + (y - mid) * 1.5) for x, y in poly]
    ink, _ = masks(side, [polys[0]] + [taller(q) for q in polys[1:]])
    img = Image.new("RGBA", (side, side), (0, 0, 0, 255))
    img.putalpha(ink)
    return img


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    polys = mark_polys()

    for name, size in [
        ("32x32.png", 32), ("128x128.png", 128),
        ("128x128@2x.png", 256), ("icon.png", 512),
    ]:
        app_icon(size, polys).save(OUT / name)

    # macOS menu bar: 18 pt, so 18 px @1x and 36 px @2x.
    tray_icon(18, polys).save(OUT / "tray.png")
    tray_icon(36, polys).save(OUT / "tray@2x.png")

    # .icns for the macOS bundle.
    iconset = OUT / "icon.iconset"
    shutil.rmtree(iconset, ignore_errors=True)
    iconset.mkdir()
    for size in (16, 32, 128, 256, 512):
        app_icon(size, polys).save(iconset / f"icon_{size}x{size}.png")
        app_icon(size * 2, polys).save(iconset / f"icon_{size}x{size}@2x.png")
    subprocess.run(["iconutil", "-c", "icns", str(iconset), "-o", str(OUT / "icon.icns")],
                   check=True)
    shutil.rmtree(iconset, ignore_errors=True)

    print("wrote:", ", ".join(sorted(p.name for p in OUT.iterdir())))


if __name__ == "__main__":
    main()
